[package]
name = "cc_22"
version = "1.0.0"
edition = "2021"
authors = ["Rafa Audio"]
description = "CC-22 — a boutique modular multi-FX plugin (Character, Movement, Diffusion, Texture)."
repository = "https://github.com/overidiz/cc-22"
license-file = "EULA.md"

[workspace]
members = [".", "xtask"]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cc22-standalone"
path = "src/main.rs"

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "f36931f", features = ["standalone"] }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug.git", rev = "f36931f" }

[build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
